spring:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
