server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator: true
      routes:
        # User Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**
            - Path=/api/permissions/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        # Board Service
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/boards/**
            - Path=/api/columns/**
          filters:
            - StripPrefix=1

    loadbalancer:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE # Основные логи маршрутизации
    reactor.netty.http.client: DEBUG # Логи HTTP клиента
