server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator: false
      routes:
        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/users/**
          filters:
            - RemoveRequestHeader=X-User-Id
            - StripPrefix=1

        # Board Service
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/boards/**,/api/columns/**
          filters:
            - RemoveRequestHeader=X-User-Id
            - StripPrefix=1

    loadbalancer:
      enabled: true
