spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

logging:
  level:
    root: INFO
    org.springframework.web: WARN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
