jwt:
  publicRsaFile: |
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FR
    OEFNSUlCQ2dLQ0FRRUF2ckpNQWx3KzJ4cGRhQVNhWFZMKwoxY1I2R05qMDdYUVV3cG1ONEtxblpn
    ZkFIVWlSeUZoM2R1NTY0SzNkSllONk9HL0ZQNCtFMTh6eVEzMW1TVmx3ClF6NkZ2Wm9ha09uTlNM
    SDZKVU9KL1ZGYXk2Wng2SFd4MTNKNElhNWUrWGt1U0lMRGRIVzdYakRnNWVpOERTdEcKVTIxV09h
    eHZ0Qi9mQkpNSWVLT2lSMCtkN3Bpa1o5bGJBMlpUZ09tdmcvY0VDWUlkbW13d29sQWdQa0F1VTZt
    cApoM0hHTW04UG1nTWc3bnpHcXpKcEZyVllGcHhXME54SHYwczQyZmhkZ3puZHdvMDZEUHIvZHlD
    dmtBRk1VempHCkVBYk90UmFFNm5pOFVoYWkvN2tVUkY4TEtRc1JkOTRTeUw0Zi9zOElYNS9uYSta
    N1B3WlBKQ2c1azNubGlsL0kKWHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
