spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_JDBC_URL}/${DATABASE_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8082
