spring:
  datasource:
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}

jwt:
  privateRsaFile: |
    TUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDK3Nrd0NY
    RDdiR2wxbwpCSnBkVXY3VnhIb1kyUFR0ZEJUQ21ZM2dxcWRtQjhBZFNKSElXSGQyN25yZ3JkMGxn
    M280YjhVL2o0VFh6UEpECmZXWkpXWEJEUG9XOW1ocVE2YzFJc2ZvbFE0bjlVVnJMcG5Ib2RiSFhj
    bmdocmw3NWVTNUlnc04wZGJ0ZU1PRGwKNkx3TkswWlRiVlk1ckcrMEg5OEVrd2g0bzZKSFQ1M3Vt
    S1JuMlZzRFpsT0E2YStEOXdRSmdoMmFiRENpVUNBKwpRQzVUcWFtSGNjWXlidythQXlEdWZNYXJN
    bWtXdFZnV25GYlEzRWUvU3pqWitGMkRPZDNDalRvTSt2OTNJSytRCkFVeFRPTVlRQnM2MUZvVHFl
    THhTRnFML3VSUkVYd3NwQ3hGMzNoTEl2aC8rendoZm4rZHI1bnMvQms4a0tEbVQKZWVXS1g4aGZB
    Z01CQUFFQ2dnRUFSUVR6VGNkbFdKZnFSc09qdXpOVzJMZ01HUUl0WStRbnYyY2tXclJwY2h4TQpC
    RTFIdG1PT21aVW5GRHJaVjhLR2NmYkNSWWNFWmJiZjJGMkNyL21YRUQrSTJGNzJUb3pRcUFjQ3Fv
    b1BYNGdhCmZLcjVmMUZaMU1peGdqOUNVTGp6YjNza2t2b3BucVhDUUhSRDIrQlZ5OHcrOFJEZ1BT
    bHI1cFB3OVBrRXV4b04KVGp2VlhJNkVNMzgweFg4Qzhwd3RzZndPWmkyeWVmaGZaNFhwc0hyN3dY
    dGU0SXM2ejQ3WlpoTXd4V0l4ZzZNTwpldmxIQ0hFYUNqcy83SEFCbFVhZk9scWpIWWhOd2xjamw0
    WWs4dG4rZFJRMS9XZjJPRDdLa25FcHpDenpXWktTCnNqQTJ5NVlZd1ltT2p6d2NOQ1FyT2dqNXBQ
    Tmt4bFNTQ1BiUFRsK0xBUUtCZ1FEeDdYRXNCRVhtdFNUU2xIeUcKV2tYcUtUS0VqSGRFNGhMLzRk
    OW8xUmxwRFgrRkpCcUs1aVNsQ2ZPZ3o2b0Q4QmtsaCtPRTYyaDViNi9OdEJiVQphbEF1amVxTWdh
    VTMwMW5ZeWR5NnI1WTJQeXBKT09GNTR5NlJCOFhUVHlqWkR3Q1NOYkNwVzJkS05RQTYvcm5ZCmFu
    RVFqYWF6T3VwMC9mL1FSekF1aDFqQzd3S0JnUURKeWZoZ05ablYyVkJaN3VPem9zQTFGK1U0Mk5B
    aCtmaE0KVHpKa3VVK2ZrMWNDZ011THdLRXIrWGVML2dsOGZIaEJ4bFB6ejBMcENtUWpKS3hJNDZO
    dzIyenFQV3MrUGtZSwpnYWZ1VzdtRHB0NzkvOC84UXhIWU42QXk3SDlRU3FHWmN4c2J2cnRLaGhN
    eXNzZHhrdXhkSmJHZitmUGJtU1lwCm11OW1VRkNSa1FLQmdRQytwVXVDMFZjNGFGVTlNTkEwbTl6
    dW0wcDVFNnhGZHhaYjJPWlNXV1B0MmpvOGRHZ0sKUHpSdmJqa3o1NUhtQ29YMmduQno1WUx0OTJx
    RjRyMys1RXlOY3o1N1BRc3l3L1hRbGJyQXp1L0RqZUZIMUhBeQp1aW1QRnAzNVdDOHJaZHdnVy9q
    OGJOQW50VDZhUHZPN0xKNHUya0djaWZnSys4Smtva1RBMWQzSHR3S0JnUURHCkUxNmV1aDdPbnVu
    VHpiNXdGOE1LbXZFajh4ZWpNbWQ4S0lWei83OWNDZHB3RjVNMkZKbGd2Qm1RTG9hTFR2Y1EKd2Fp
    bysvdFhIQjhkckNMOXpZNGkreEVYZ2NDaXNhZzVLZnA0N0VyWEkxZGpCdGZYYk5LNFppbjNzdFJx
    TVVnZApnN0xKY2xrUWx6bURHNkRSS0lLaUVKMGlSczRMOG5KV2hzS1dzU0hWTVFLQmdCeVZ6ZnZj
    V0VhbURobDByMlBOCnh3UUhLSEFrVG5VSGcwZFIwaXBTaHpPTlVMbHZaTUd0S1ViZDZKNkpNYUtK
    eWZ5b3UvNXFDSURLTndSNE1XVGMKb3J0U2IvczJrN056ZlNSMllTZGZQTVB2MHErcTMzM3ZnalVH
    TmNvSGZCQ080QTkwQzM5bGpwREpoM1V3MjVQOApHcFZHUkV2ZElBdTFiMXlrUkJlVWIyUHEK

cors:
  allowed-origins: "http://localhost:3000" # TODO change to env var later
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type"
