# user-service (prod)
server:
  port: 8080

database:
  url: jdbc:postgresql://prod-db:5432/users_prod
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

feature-flags:
  enable-experimental-api: false
  cache-ttl: 5m
