spring:
  datasource:
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}

jwt:
  privateRsaFile: classpath:dev-keys/private.txt

cors:
  allowed-origins: "http://localhost:3000" # TODO change to env var later
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type"
