spring:
  datasource:
    username: $(POSTGRES_USER:admin)
    password: $(POSTGRES_PASS:admin)

app:
  jwt:
    secret: your-256-bit-secret-key-here

cors:
  allowed-origins: "http://localhost:3000" # TODO change to env var later
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type"
