spring:
  datasource:
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}

jwt:
  privateRsaFile: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRQytza3dDWEQ3YkdsMW8KQkpwZFV2N1Z4SG9ZMlBUdGRCVENt
    WTNncXFkbUI4QWRTSkhJV0hkMjducmdyZDBsZzNvNGI4VS9qNFRYelBKRApmV1pKV1hCRFBvVzlt
    aHFRNmMxSXNmb2xRNG45VVZyTHBuSG9kYkhYY25naHJsNzVlUzVJZ3NOMGRidGVNT0RsCjZMd05L
    MFpUYlZZNXJHKzBIOThFa3doNG82SkhUNTN1bUtSbjJWc0RabE9BNmErRDl3UUpnaDJhYkRDaVVD
    QSsKUUM1VHFhbUhjY1l5YncrYUF5RHVmTWFyTW1rV3RWZ1duRmJRM0VlL1N6alorRjJET2QzQ2pU
    b00rdjkzSUsrUQpBVXhUT01ZUUJzNjFGb1RxZUx4U0ZxTC91UlJFWHdzcEN4RjMzaExJdmgvK3p3
    aGZuK2RyNW5zL0JrOGtLRG1UCmVlV0tYOGhmQWdNQkFBRUNnZ0VBUlFUelRjZGxXSmZxUnNPanV6
    TlcyTGdNR1FJdFkrUW52MmNrV3JScGNoeE0KQkUxSHRtT09tWlVuRkRyWlY4S0djZmJDUlljRVpi
    YmYyRjJDci9tWEVEK0kyRjcyVG96UXFBY0Nxb29QWDRnYQpmS3I1ZjFGWjFNaXhnajlDVUxqemIz
    c2trdm9wbnFYQ1FIUkQyK0JWeTh3KzhSRGdQU2xyNXBQdzlQa0V1eG9OClRqdlZYSTZFTTM4MHhY
    OEM4cHd0c2Z3T1ppMnllZmhmWjRYcHNIcjd3WHRlNElzNno0N1paaE13eFdJeGc2TU8KZXZsSENI
    RWFDanMvN0hBQmxVYWZPbHFqSFloTndsY2psNFlrOHRuK2RSUTEvV2YyT0Q3S2tuRXB6Q3p6V1pL
    UwpzakEyeTVZWXdZbU9qendjTkNRck9najVwUE5reGxTU0NQYlBUbCtMQVFLQmdRRHg3WEVzQkVY
    bXRTVFNsSHlHCldrWHFLVEtFakhkRTRoTC80ZDlvMVJscERYK0ZKQnFLNWlTbENmT2d6Nm9EOEJr
    bGgrT0U2Mmg1YjYvTnRCYlUKYWxBdWplcU1nYVUzMDFuWXlkeTZyNVkyUHlwSk9PRjU0eTZSQjhY
    VFR5alpEd0NTTmJDcFcyZEtOUUE2L3JuWQphbkVRamFhek91cDAvZi9RUnpBdWgxakM3d0tCZ1FE
    SnlmaGdOWm5WMlZCWjd1T3pvc0ExRitVNDJOQWgrZmhNClR6Smt1VStmazFjQ2dNdUx3S0VyK1hl
    TC9nbDhmSGhCeGxQenowTHBDbVFqSkt4STQ2TncyMnpxUFdzK1BrWUsKZ2FmdVc3bURwdDc5Lzgv
    OFF4SFlONkF5N0g5UVNxR1pjeHNidnJ0S2hoTXlzc2R4a3V4ZEpiR2YrZlBibVNZcAptdTltVUZD
    UmtRS0JnUUMrcFV1QzBWYzRhRlU5TU5BMG05enVtMHA1RTZ4RmR4WmIyT1pTV1dQdDJqbzhkR2dL
    ClB6UnZiamt6NTVIbUNvWDJnbkJ6NVlMdDkycUY0cjMrNUV5TmN6NTdQUXN5dy9YUWxickF6dS9E
    amVGSDFIQXkKdWltUEZwMzVXQzhyWmR3Z1cvajhiTkFudFQ2YVB2TzdMSjR1MmtHY2lmZ0srOEpr
    b2tUQTFkM0h0d0tCZ1FERwpFMTZldWg3T251blR6YjV3RjhNS212RWo4eGVqTW1kOEtJVnovNzlj
    Q2Rwd0Y1TTJGSmxndkJtUUxvYUxUdmNRCndhaW8rL3RYSEI4ZHJDTDl6WTRpK3hFWGdjQ2lzYWc1
    S2ZwNDdFclhJMWRqQnRmWGJOSzRaaW4zc3RScU1VZ2QKZzdMSmNsa1Fsem1ERzZEUktJS2lFSjBp
    UnM0TDhuSldoc0tXc1NIVk1RS0JnQnlWemZ2Y1dFYW1EaGwwcjJQTgp4d1FIS0hBa1RuVUhnMGRS
    MGlwU2h6T05VTGx2Wk1HdEtVYmQ2SjZKTWFLSnlmeW91LzVxQ0lES053UjRNV1RjCm9ydFNiL3My
    azdOemZTUjJZU2RmUE1QdjBxK3EzMzN2Z2pVR05jb0hmQkNPNEE5MEMzOWxqcERKaDNVdzI1UDgK
    R3BWR1JFdmRJQXUxYjF5a1JCZVViMlBxCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

cors:
  allowed-origins: "http://localhost:3000" # TODO change to env var later
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type"
